// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw9sGrmdVwweXabdmUlABz3M-SfjaasfA',
    appId: '1:789371925380:web:ae3e74ecd4092bba7a63d1',
    messagingSenderId: '789371925380',
    projectId: 'hamburguesas-c0315',
    authDomain: 'hamburguesas-c0315.firebaseapp.com',
    storageBucket: 'hamburguesas-c0315.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdh_YTR0EQ_IaHHgHWQfiRJ3WB9mK3fME',
    appId: '1:789371925380:android:be88425a2fe1e2af7a63d1',
    messagingSenderId: '789371925380',
    projectId: 'hamburguesas-c0315',
    storageBucket: 'hamburguesas-c0315.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA82a-0eyVuT1srLljDajHwyifwZ_v3Qko',
    appId: '1:789371925380:ios:3960afefdadec3097a63d1',
    messagingSenderId: '789371925380',
    projectId: 'hamburguesas-c0315',
    storageBucket: 'hamburguesas-c0315.firebasestorage.app',
    iosBundleId: 'com.example.flutterHamburgesas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA82a-0eyVuT1srLljDajHwyifwZ_v3Qko',
    appId: '1:789371925380:ios:3960afefdadec3097a63d1',
    messagingSenderId: '789371925380',
    projectId: 'hamburguesas-c0315',
    storageBucket: 'hamburguesas-c0315.firebasestorage.app',
    iosBundleId: 'com.example.flutterHamburgesas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw9sGrmdVwweXabdmUlABz3M-SfjaasfA',
    appId: '1:789371925380:web:aa16a028bd62fe217a63d1',
    messagingSenderId: '789371925380',
    projectId: 'hamburguesas-c0315',
    authDomain: 'hamburguesas-c0315.firebaseapp.com',
    storageBucket: 'hamburguesas-c0315.firebasestorage.app',
  );
}
